### ISSUE TITLE
vibrantLinux does not launch in Ubuntu 20.04

### ISSUE THREAD

**Issue by ottercat78** [flathub/io.github.libvibrant.vibrantLinux#1]
Hello,

I installed vibrantLinux on Ubuntu 20.04 (flatpak install flathub io.github.libvibrant.vibrantLinux). It went fine, the app showed in app search, but when I clicked on it, only the icon blinked and did not launch. I uninstalled it (flatpak uninstall --all) and installed it again, but this did not help. Can this be fixed?

Thanks

**Comment by Tiagoquix** [comment]
@Scrumplex Please move the issue to the appropriate repository. Thanks!

**Comment by Scrumplex** [comment]
I don't think I can transfer it between organizations. @ottercat78 Do you still have this issue?

**Comment by ottercat78** [comment]
Please disregard.
